name = "16AA public mods"
prefix = "LSR"
author = "16AA 3LSR"
version = "0.0.0"
files = ["mod.cpp"]
sigversion = 3
signame = "16aa-3lsr-{{date \"%Y\"}}-{{date \"%m\"}}-{{date \"%d\"}}"
keyname = "16aa-3lsr-{{date \"%Y\"}}-{{date \"%m\"}}-{{date \"%d\"}}"
reuse_private_key = false
include = ["./include"]
exclude = [".swp"]
