name = "16AA public mods"
prefix = "LSR"
author = "16AA 3LSR"
version = "0.0.0" # NB: this is not the real version number. We use git tags.
files = ["mod.cpp","*.paa","LICENSE"]
sigversion = 3
signame = "16aa-3lsr-{{date \"%Y\"}}-{{date \"%m\"}}-{{date \"%d\"}}.{{git \"id 4\"}}"
keyname = "16aa-3lsr-{{date \"%Y\"}}-{{date \"%m\"}}-{{date \"%d\"}}.{{git \"id 4\"}}"
reuse_private_key = false
include = ["./include"]
exclude = [".swp"]
