class CfgVehicles {
    class Land_OrthodoxChurch_02_F;
    class Land_Church_05_F;
    class Land_Church_02a: Land_OrthodoxChurch_02_F {};
    class Land_Church_02: Land_OrthodoxChurch_02_F {};
    class Land_Church_01: Land_Church_05_F {};
    class Land_House_1W04_F;
    class Land_House_2B04_F;
    class Land_House_1W07_F;
    class Land_House_1W01_F;
    class Land_House_1W10_F;
    class Land_House_1W02_F;
    class Land_House_2W02_F;
    class Land_House_2B02_F;
    class Land_House_2B01_F;
    class Land_House_2B03_F;
    class Land_House_2W03_F;
    class Land_House_1W08_F;
    class Land_House_1B01_F;
    class Land_House_1W11_F;
    class Land_House_1W05_F;
    class Land_House_2W04_F;
    class Land_House_2W01_F;
    class Land_House_1W03_F;
    class Land_House_1W06_F;
    class Land_House_1W09_F;
    class Land_HouseV_2I: Land_House_1B01_F {};
    class Land_HouseV_2L: Land_House_2B01_F {};
    class Land_HouseV2_02: Land_House_2B02_F {};
    class Land_HouseV2_03B: Land_House_2B03_F {};
    class Land_HouseV2_04_interier: Land_House_2B04_F {};
    class Land_HouseV_1I1: Land_House_1W01_F {};
    class Land_HouseV_3I3: Land_House_1W10_F {};
    class Land_HouseV_3I4: Land_House_1W11_F {};
    class Land_HouseV_1I2: Land_House_1W02_F {};
    class Land_HouseV_1I3: Land_House_1W03_F {};
    class Land_HouseV_1I4: Land_House_1W04_F {};
    class Land_HouseV_1L1: Land_House_1W05_F {};
    class Land_HouseV_1L2: Land_House_1W06_F {};
    class Land_HouseV_1T: Land_House_1W07_F {};
    class Land_HouseV_3I1: Land_House_1W08_F {};
    class Land_HouseV_3I2: Land_House_1W09_F {};
    class Land_houseV_2T1: Land_House_2W01_F {};
    class Land_houseV_2T2: Land_House_2W02_F {};
    class Land_HouseV2_01A: Land_House_2W03_F {};
    class Land_HouseV2_01B: Land_House_2W04_F {};
};
