class CfgVehicles {
    delete Land_HouseV_2I;
    delete Land_HouseV_2L;
    delete Land_HouseV2_02;
    delete Land_HouseV2_03B;
    delete Land_HouseV2_04_interier;
    delete Land_HouseV_1I1;
    delete Land_HouseV_3I3;
    delete Land_HouseV_3I4;
    delete Land_HouseV_1I2;
    delete Land_HouseV_1I3;
    delete Land_HouseV_1I4;
    delete Land_HouseV_1L1;
    delete Land_HouseV_1L2;
    delete Land_HouseV_1T;
    delete Land_HouseV_3I1;
    delete Land_HouseV_3I2;
    delete Land_houseV_2T1;
    delete Land_houseV_2T2;
    delete Land_HouseV2_01A;
    delete Land_HouseV2_01B;
    delete Land_Church_02a;
    delete Land_Church_02;
    delete Land_Church_01;
};
