on:
  push:
    branches:
      - master

jobs:
  build_addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build addon with HEMTT
        uses: arma-actions/hemtt@master
